### ISSUE TITLE
Rundeck shows error on startup on CentOS 7.6

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-rundeck#10]
**Describe the bug**
Got this per email from Christian:

```
Hello Robert,

I recently downloaded your rundeck role from galaxy community, looks
very nice thank you for sharing.

I have only one question, when I deploy rundeck into my CentOS 7.6 the
service starts for a few seconds and after that fails and display the
following error:

Have you run into this problem?
```

```
[21:15][vagrant@rundeck][~]$ systemctl status rundeck
   rundeck.service - Rundeck
    Loaded: loaded (/etc/systemd/system/rundeck.service; enabled; vendor
preset: disabled)
    Active: failed (Result: exit-code) since lun 2019-09-30 21:14:25
UTC; 55s ago
   Process: 16464 ExecStart=/usr/bin/java -Xmx1024m -Xms256m
-XX:MaxMetaspaceSize=128m -server -Dserver.web.context=/
-Dserver.http.host=10.2.0.41 -Dserver.http.port=4440 -jar
/opt/rundeck/rundeck-3.1.0-20190731.war (code=exited, status=1/FAILURE)
  Main PID: 16464 (code=exited, status=1/FAILURE)



21:15][root@rundeck][/home/vagrant]$ /usr/bin/java -Xmx1024m -Xms256m
-XX:MaxMetaspaceSize=128m -server -Dserver.web.context=/
-Dserver.http.host=10.2.0.41 -Dserver.http.port=4440 -jar
/opt/rundeck/rundeck-3.1.0-20190731.war

Configuring Spring Security Core ...
... finished configuring Spring Security Core

[2019-09-30 21:16:08.699] ERROR GrailsApplicationPostProcessor ---
[           main] Error loading spring/resources.groovy file: The
provided File object is not a directory: /opt/rundeck/libext

java.lang.IllegalArgumentException: The provided File object is not a
directory: /opt/rundeck/libext
     at
org.codehaus.groovy.runtime.ResourceGroovyMethods.checkDir(ResourceGroovyMethods.java:1065)
     at
org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileMatch(ResourceGroovyMethods.java:1437)
     at org.codehaus.groovy.runtime.dgm$940.invoke(Unknown Source)
     at
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
     at
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
     at
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
     at resources$_run_closure1.doCall(resources.groovy:368)
     at resources$_run_closure1.doCall(resources.groovy)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
     at
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
     at groovy.lang.Closure.call(Closure.java:418)
     at groovy.lang.Closure.call(Closure.java:412)
     at
grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
     at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
     at
org.grails.spring.RuntimeSpringConfigUtilities.reloadSpringResourcesConfig(RuntimeSpringConfigUtilities.java:103)
     at
grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:181)
     at
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
     at
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
     at
org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
     at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
     at
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
     at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
     at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
     at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
     at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
     at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
     at grails.boot.GrailsApp$run.call(Unknown Source)
     at
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
     at rundeckapp.Application.main(Application.groovy:28)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
     at
org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)

[2019-09-30 21:16:08.744] ERROR SpringApplication --- [ main]
Application startup failed

org.grails.core.exceptions.GrailsConfigurationException: Error loading
spring/resources.groovy file: The provided File object is not a
directory: /opt/rundeck/libext
     at
grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:184)
     at
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
     at
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
     at
org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
     at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
     at
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
     at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
     at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
     at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
     at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
     at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
     at grails.boot.GrailsApp$run.call(Unknown Source)
     at
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
     at rundeckapp.Application.main(Application.groovy:28)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
     at
org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.IllegalArgumentException: The provided File object
is not a directory: /opt/rundeck/libext
     at
org.codehaus.groovy.runtime.ResourceGroovyMethods.checkDir(ResourceGroovyMethods.java:1065)
     at
org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileMatch(ResourceGroovyMethods.java:1437)
     at org.codehaus.groovy.runtime.dgm$940.invoke(Unknown Source)
     at
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
     at
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
     at
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
     at
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
     at resources$_run_closure1.doCall(resources.groovy:368)
     at resources$_run_closure1.doCall(resources.groovy)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
     at
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
     at groovy.lang.Closure.call(Closure.java:418)
     at groovy.lang.Closure.call(Closure.java:412)
     at
grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
     at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
     at
org.grails.spring.RuntimeSpringConfigUtilities.reloadSpringResourcesConfig(RuntimeSpringConfigUtilities.java:103)
     at
grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:181)
     ... 24 common frames omitted
```
I'll try to reproduce this issue and get back later.

Thanks Christian for your feedback!

**Comment by robertdebock** [comment]
I can reproduce the issue. Working on a fix.

**Comment by robertdebock** [comment]
Please wait the release to galaxy, later today.
