### ISSUE TITLE
Issue for sampling hello world job execution after install

### ISSUE THREAD

**Issue by jhanssenfavaro** [robertdebock/ansible-role-rundeck#22]
## Describe the bug

Not able to run simple job after install. I know it's much more a rundeck configuration related issue than your role definition, but would be nice to have a valida rundeck configuration working as sample project.

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```bash
---
#!/bin/bash
echo "hello world is working"
```

## Output

`Aug 04 13:59:30 new-rundeck-vm-0 java[96400]: [2023-08-04T13:59:30,857] ERROR services.ExecutionUtilService [quartzScheduler_Worker-1] - Execution failed: 4 in project sample_project: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [new-rundeck-vm-0: Unknown: java.lang.NullPointerException]}, Node failures: {new-rundeck-vm-0=[Unknown: java.lang.NullPointerException]}, status: failed]`

```

[workflow] Begin execution: node-first
preparing for sequential execution on 1 nodes
Executing command on node: new-rundeck-vm-0, NodeEntryImpl{tags=[], attributes={nodename=new-rundeck-vm-0, hostname=new-rundeck-vm-0, osVersion=6.1.38-59.109.amzn2023.x86_64, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux}, project='null'}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Start EngineWorkflowExecutor
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Update conditional state: {before.step.1=true, after.step.1=false}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] start conditions for step [1]: []
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] skip conditions for step [1]: [(step.1.completed == 'true')]
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Create rule engine with rules: RuleEngine{ruleSet=[Rule: Conditions([]) => DataState{state={step.1.start=true}}, Rule: Conditions([(step.any.flowcontrol.halt == 'true')]) => DataState{state={workflow.done=true}}, Rule: Conditions([(step.any.state.failed == 'true'), (workflow.keepgoing == 'false')]) => DataState{state={workflow.done=true}}, Rule: Conditions([java.util.function.Predicate$$Lambda$595/0x00007f1a342ec0d0@5e3798db]) => DataState{state={step.1.skip=true}}]}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Create workflow engine with state: StateLogger{state=DataState{state={workflow.id=40e0f7f3-d94b-466f-919a-1922ab367927, workflow.keepgoing=false, before.step.1=true, after.step.1=false}}}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Begin: Workflow begin
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] WillProcessStateChange: state changes: init DataState{state={workflow.state=started}}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Update conditional state: {workflow.state=started}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Update conditional state: {step.1.start=true}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] DidProcessStateChange: applied state changes and rules (changed? true): init - StateLogger{state=DataState{state={workflow.id=40e0f7f3-d94b-466f-919a-1922ab367927, workflow.keepgoing=false, before.step.1=true, step.1.start=true, after.step.1=false, workflow.state=started}}}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] WillRunOperation: operation starting: Step{stepNum=1, label='null'}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] LoopProgress: Pending(1) => run(1), skip(0), remain(0)
[workflow] Begin step: 1,NodeDispatch
1: Workflow step executing: ScriptFileItem{script=[41 chars]}
preparing for sequential execution on 1 nodes
Executing command on node: new-rundeck-vm-0, NodeEntryImpl{tags=[], attributes={nodename=new-rundeck-vm-0, hostname=new-rundeck-vm-0, osVersion=6.1.38-59.109.amzn2023.x86_64, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux}, project='null'}
[workflow] beginExecuteNodeStep(new-rundeck-vm-0): NodeDispatch: ScriptFileItem{script=[41 chars]}
[workflow] finishExecuteNodeStep(new-rundeck-vm-0): NodeDispatch: Unknown: null
Failed dispatching to node new-rundeck-vm-0: java.lang.NullPointerException
Failed dispatching to node new-rundeck-vm-0: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: java.lang.NullPointerException
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:221)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:130)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:61)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:263)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:234)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:111)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:285)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:681)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:76)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:32)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$beginOperation$1(WorkflowEngineOperationsProcessor.java:323)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.dtolabs.rundeck.core.execution.script.ScriptfileUtils.createTempFile(ScriptfileUtils.java:301)
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:134)
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:83)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.writeScriptToTempFile(DefaultScriptFileNodeStepUtils.java:184)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:110)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:81)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:207)
	... 18 more
1: Workflow step finished, result: NodeDispatchFailure: Failed dispatching to node new-rundeck-vm-0: java.lang.NullPointerException
[workflow] Finish step: 1,NodeDispatch
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] OperationFailed: operation completed, success? false: OperationCompleted(identity=[1], stepNum=1, newState=DataState{state={step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}, stepResultCapture=StepResultCapture{stepResult=NodeDispatchFailure: Failed dispatching to node new-rundeck-vm-0: java.lang.NullPointerException, stepSuccess=false, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={}, base=null)}, success=false)
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] WillProcessStateChange: state changes: [1] DataState{state={step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Update conditional state: {step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Update conditional state: {workflow.done=true, step.1.start=true, step.1.skip=true}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] DidProcessStateChange: applied state changes and rules (changed? true): [1] - StateLogger{state=DataState{state={workflow.id=40e0f7f3-d94b-466f-919a-1922ab367927, workflow.keepgoing=false, workflow.done=true, step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.start=true, after.step.1=true, step.1.state=failure, workflow.state=started, step.1.skip=true}}}
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] WorkflowEndState: Workflow end state reached.
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] WillShutdown: Workflow engine shutting down (interrupted? false)
[wf:40e0f7f3-d94b-466f-919a-1922ab367927] Complete: Workflow complete: [Step{stepNum=1, label='null'}: OperationCompleted(identity=[1], stepNum=1, newState=DataState{state={step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}, stepResultCapture=StepResultCapture{stepResult=NodeDispatchFailure: Failed dispatching to node new-rundeck-vm-0: java.lang.NullPointerException, stepSuccess=false, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={}, base=null)}, success=false)]
[workflow] Finish execution:  node-first: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [new-rundeck-vm-0: Unknown: java.lang.NullPointerException]}, Node failures: {new-rundeck-vm-0=[Unknown: java.lang.NullPointerException]}, status: failed]
[Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [new-rundeck-vm-0: Unknown: java.lang.NullPointerException]}, Node failures: {new-rundeck-vm-0=[Unknown: java.lang.NullPointerException]}, status: failed]
Execution failed: 3 in project sample_project: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [new-rundeck-vm-0: Unknown: java.lang.NullPointerException]}, Node failures: {new-rundeck-vm-0=[Unknown: java.lang.NullPointerException]}, status: failed]
```

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)
```
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Feb 23 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)
```
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```
Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by jhanssenfavaro** [comment]
https://github.com/rundeck/rundeck/issues/8142

Apparently there was someone facing this same issue...

**Comment by jhanssenfavaro** [comment]
never mind... for whoever is getting same error it's much more related to keys path location at project level than any other error.

**Comment by jhanssenfavaro** [comment]
Correction after taking a look on rundeck's code, the missing property was identified: 
framework.file-copy-destination-dir = /opt/rundeck/tmp
**framework.tmp.dir=/opt/rundeck/tmp**

Just add that to your framework.properties and that should work
